### ISSUE TITLE
Solar power

### ISSUE THREAD

**Issue by dloeckx** [grahamwhaley/ESP32-T5-clock#1]
Dear @grahamwhaley , I read about this interesting project of you in a [thread](https://github.com/lewisxhe/TTGO-EPaper-Series/issues/16) in the TTGO EPaper repo. I want to build a wireless and preferably solar powered (pool) thermometer with this board. Can you share your experience with solar powering? I am especially interested to learn if you can connect a solar panel directly to the board (through `+5V` I would assume)?

**Comment by grahamwhaley** [comment]
Hi @dloeckx - sure, I'll tell you what I know so far, but it's not too much.

I think the answer is yes, you should be able to connect a 5v solar panel directly to the board. I don't think you can/want to connect it to the 5v pins though, but to the USB port VBUS. You need to feed the tp4054 (charger chip - the pdf is available, but can be hard to find - the chip is made by 'NanJing Top Power' afaict), and it is not fed from the '5v' rail, only the 'vbus' rail.

What I did as an on-going experiment is to buy a small 5v solar panel, and wire it into the micro USB socket, along with a lipo battery on the battery connector. Here is a picture:

![solar_clock](https://user-images.githubusercontent.com/4761717/108385363-806c9480-7203-11eb-97d6-f30f7a9d4b87.JPG)

I don't actually have it running the clock code, due to the clock drift 'bug'. It is currently running some weather station code. It has been running for 1 month so far, and the battery is still showing 100%. It is very hard for me to measure the solar panel power output and/or charge current though, so I cannot be certain the panel is charging the battery, particularly as it is sat indoors in the shade right now!

But, for you application I presume you may be able to have a larger panel and position it outdoors - in which case I think yes, you should be able to make this work!

I do think you will want to remove the 'charging led' from the board - you may want to leave it in place initially if you have a large enough solar panel so you can verify it is charging!, but ultimately that is consuming your solar power for no reason... also remove the 'power' led from the board :-)

Good luck!
